import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialSchema1779143493726 implements MigrationInterface {
    name = 'InitialSchema1779143493726'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "tenants" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "slug" character varying NOT NULL, "name" character varying NOT NULL, "industry" character varying, "logo" character varying, "website" character varying, "contact_email" character varying, "contact_phone" character varying, "address" character varying, "province" character varying NOT NULL DEFAULT 'QC', "keycloak_realm" character varying, "max_employees" integer NOT NULL DEFAULT '100', "is_active" boolean NOT NULL DEFAULT true, "subscription_plan" character varying NOT NULL DEFAULT 'starter', "subscription_expires_at" TIMESTAMP WITH TIME ZONE, "settings" jsonb, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_2310ecc5cb8be427097154b18fc" UNIQUE ("slug"), CONSTRAINT "PK_53be67a04681c66b87ee27c9321" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "departments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "description" character varying, "code" character varying, "manager_id" uuid, "parent_department_id" uuid, "tenant_id" uuid NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_839517a681a86bb84cbcc6a1e9d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "positions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "title" character varying NOT NULL, "description" character varying, "min_salary" numeric(12,2), "max_salary" numeric(12,2), "is_active" boolean NOT NULL DEFAULT true, "department_id" uuid, "tenant_id" uuid NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_17e4e62ccd5749b289ae3fae6f3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."shifts_status_enum" AS ENUM('SCHEDULED', 'IN_PROGRESS', 'COMPLETED', 'ABSENT', 'CANCELLED')`);
        await queryRunner.query(`CREATE TABLE "shifts" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "start_time" TIMESTAMP WITH TIME ZONE NOT NULL, "end_time" TIMESTAMP WITH TIME ZONE NOT NULL, "actual_start_time" TIMESTAMP WITH TIME ZONE, "actual_end_time" TIMESTAMP WITH TIME ZONE, "status" "public"."shifts_status_enum" NOT NULL DEFAULT 'SCHEDULED', "location" character varying, "location_lat" numeric(10,7), "location_lng" numeric(10,7), "notes" character varying, "is_overtime" boolean NOT NULL DEFAULT false, "overtime_rate" numeric(5,2) NOT NULL DEFAULT '1.5', "break_duration_minutes" integer NOT NULL DEFAULT '0', "employee_id" uuid NOT NULL, "tenant_id" uuid NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_84d692e367e4d6cdf045828768c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."leaves_type_enum" AS ENUM('VACATION', 'SICK', 'PERSONAL', 'MATERNITY', 'PATERNITY', 'BEREAVEMENT', 'UNPAID', 'PARENTAL', 'JURY_DUTY', 'COMPASSIONATE')`);
        await queryRunner.query(`CREATE TYPE "public"."leaves_status_enum" AS ENUM('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED')`);
        await queryRunner.query(`CREATE TABLE "leaves" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "type" "public"."leaves_type_enum" NOT NULL, "status" "public"."leaves_status_enum" NOT NULL DEFAULT 'PENDING', "start_date" date NOT NULL, "end_date" date NOT NULL, "total_days" numeric(5,1) NOT NULL, "reason" character varying, "rejection_reason" character varying, "approved_at" TIMESTAMP WITH TIME ZONE, "approved_by_id" uuid, "medical_certificate_url" character varying, "employee_id" uuid NOT NULL, "tenant_id" uuid NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_4153ec7270da3d07efd2e11e2a7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."employees_status_enum" AS ENUM('ACTIVE', 'INACTIVE', 'ON_LEAVE', 'TERMINATED')`);
        await queryRunner.query(`CREATE TYPE "public"."employees_role_enum" AS ENUM('ADMIN', 'HR', 'MANAGER', 'EMPLOYEE')`);
        await queryRunner.query(`CREATE TABLE "employees" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "employee_number" character varying NOT NULL, "first_name" character varying NOT NULL, "last_name" character varying NOT NULL, "email" character varying NOT NULL, "phone_number" character varying, "avatar_url" character varying, "date_of_birth" date, "sin_number" character varying, "address" character varying, "city" character varying, "province" character varying, "postal_code" character varying, "status" "public"."employees_status_enum" NOT NULL DEFAULT 'ACTIVE', "role" "public"."employees_role_enum" NOT NULL DEFAULT 'EMPLOYEE', "hire_date" date NOT NULL, "termination_date" date, "hourly_rate" numeric(10,2), "annual_salary" numeric(12,2), "vacation_days_per_year" integer NOT NULL DEFAULT '15', "sick_days_per_year" integer NOT NULL DEFAULT '5', "keycloak_id" character varying, "custom_attributes" jsonb NOT NULL DEFAULT '{}', "department_id" uuid, "position_id" uuid, "manager_id" uuid, "tenant_id" uuid NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "created_by" uuid, "updated_by" uuid, CONSTRAINT "UQ_8878710dc844ecd6f9e587f34fc" UNIQUE ("employee_number"), CONSTRAINT "UQ_765bc1ac8967533a04c74a9f6af" UNIQUE ("email"), CONSTRAINT "UQ_e379170f85cf0bc82a4bf0d9913" UNIQUE ("keycloak_id"), CONSTRAINT "PK_b9535a98350d5b26e7eb0c26af4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."payrolls_status_enum" AS ENUM('DRAFT', 'PROCESSING', 'APPROVED', 'PAID', 'ERROR')`);
        await queryRunner.query(`CREATE TABLE "payrolls" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "period_start" date NOT NULL, "period_end" date NOT NULL, "regular_hours" numeric(8,2) NOT NULL DEFAULT '0', "overtime_hours" numeric(8,2) NOT NULL DEFAULT '0', "holiday_hours" numeric(8,2) NOT NULL DEFAULT '0', "regular_pay" numeric(12,2) NOT NULL DEFAULT '0', "overtime_pay" numeric(12,2) NOT NULL DEFAULT '0', "bonus" numeric(12,2) NOT NULL DEFAULT '0', "gross_pay" numeric(12,2) NOT NULL, "federal_tax" numeric(12,2) NOT NULL DEFAULT '0', "provincial_tax" numeric(12,2) NOT NULL DEFAULT '0', "ei_employee" numeric(10,2) NOT NULL DEFAULT '0', "ei_employer" numeric(10,2) NOT NULL DEFAULT '0', "cpp_employee" numeric(10,2) NOT NULL DEFAULT '0', "cpp_employer" numeric(10,2) NOT NULL DEFAULT '0', "rqap_employee" numeric(10,2) NOT NULL DEFAULT '0', "rqap_employer" numeric(10,2) NOT NULL DEFAULT '0', "other_deductions" numeric(12,2) NOT NULL DEFAULT '0', "total_deductions" numeric(12,2) NOT NULL, "net_pay" numeric(12,2) NOT NULL, "status" "public"."payrolls_status_enum" NOT NULL DEFAULT 'DRAFT', "nethris_export_id" character varying, "exported_at" TIMESTAMP WITH TIME ZONE, "pay_stub_url" character varying, "employee_id" uuid NOT NULL, "tenant_id" uuid NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_4fc19dcf3522661435565b5ecf3" PRIMARY KEY ("id")); COMMENT ON COLUMN "payrolls"."ei_employee" IS 'Assurance-emploi employé'; COMMENT ON COLUMN "payrolls"."ei_employer" IS 'Assurance-emploi employeur'; COMMENT ON COLUMN "payrolls"."cpp_employee" IS 'RRQ employé'; COMMENT ON COLUMN "payrolls"."cpp_employer" IS 'RRQ employeur'; COMMENT ON COLUMN "payrolls"."rqap_employee" IS 'RQAP employé (QC)'; COMMENT ON COLUMN "payrolls"."rqap_employer" IS 'RQAP employeur (QC)'`);
        await queryRunner.query(`CREATE TYPE "public"."job_applications_status_enum" AS ENUM('APPLIED', 'SCREENING', 'INTERVIEW', 'ASSESSMENT', 'OFFER', 'HIRED', 'REJECTED')`);
        await queryRunner.query(`CREATE TABLE "job_applications" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "applicant_name" character varying NOT NULL, "applicant_email" character varying NOT NULL, "applicant_phone" character varying, "resume_url" character varying, "cover_letter" text, "linkedin_profile" character varying, "status" "public"."job_applications_status_enum" NOT NULL DEFAULT 'APPLIED', "interview_date" TIMESTAMP WITH TIME ZONE, "interview_notes" text, "score" numeric(5,2), "rejection_reason" character varying, "job_posting_id" uuid NOT NULL, "assigned_to_id" uuid, "tenant_id" uuid NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_c56a5e86707d0f0df18fa111280" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."job_postings_employment_type_enum" AS ENUM('FULL_TIME', 'PART_TIME', 'CONTRACT', 'TEMPORARY', 'INTERNSHIP')`);
        await queryRunner.query(`CREATE TYPE "public"."job_postings_status_enum" AS ENUM('OPEN', 'IN_REVIEW', 'INTERVIEWING', 'OFFER_SENT', 'HIRED', 'CLOSED')`);
        await queryRunner.query(`CREATE TABLE "job_postings" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "title" character varying NOT NULL, "description" text NOT NULL, "requirements" text, "location" character varying, "is_remote" boolean NOT NULL DEFAULT false, "employment_type" "public"."job_postings_employment_type_enum" NOT NULL DEFAULT 'FULL_TIME', "salary_min" numeric(12,2), "salary_max" numeric(12,2), "status" "public"."job_postings_status_enum" NOT NULL DEFAULT 'OPEN', "published_at" TIMESTAMP WITH TIME ZONE, "closing_date" date, "linkedin_job_id" character varying, "indeed_job_id" character varying, "department_id" uuid, "recruiter_id" uuid, "tenant_id" uuid NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_dda635ece382c8ad2d90a179182" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "reviews" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "period_start" date NOT NULL, "period_end" date NOT NULL, "overall_score" numeric(4,2), "strengths" text, "areas_for_improvement" text, "goals_for_next_period" text, "employee_comments" text, "is_completed" boolean NOT NULL DEFAULT false, "completed_at" TIMESTAMP WITH TIME ZONE, "criteria" jsonb, "employee_id" uuid NOT NULL, "reviewer_id" uuid, "tenant_id" uuid NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_231ae565c273ee700b283f15c1d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "goals" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "title" character varying NOT NULL, "description" text, "target_date" date, "progress_percentage" integer NOT NULL DEFAULT '0', "is_completed" boolean NOT NULL DEFAULT false, "completed_at" TIMESTAMP WITH TIME ZONE, "employee_id" uuid NOT NULL, "tenant_id" uuid NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_26e17b251afab35580dff769223" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "trainings" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "title" character varying NOT NULL, "description" text, "provider" character varying, "category" character varying, "duration_hours" numeric(6,1), "start_date" date, "end_date" date, "is_mandatory" boolean NOT NULL DEFAULT false, "certificate_validity_months" integer, "max_participants" integer, "material_url" character varying, "online_url" character varying, "tenant_id" uuid NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_b67237502b175163e47dc85018d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."notifications_type_enum" AS ENUM('SHIFT_CHANGE', 'LEAVE_APPROVED', 'LEAVE_REJECTED', 'PAYROLL_READY', 'ANNOUNCEMENT', 'TASK_ASSIGNED', 'REVIEW_DUE', 'DOCUMENT_SHARED')`);
        await queryRunner.query(`CREATE TABLE "notifications" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "type" "public"."notifications_type_enum" NOT NULL, "title" character varying NOT NULL, "body" text NOT NULL, "is_read" boolean NOT NULL DEFAULT false, "read_at" TIMESTAMP WITH TIME ZONE, "action_url" character varying, "metadata" jsonb, "recipient_id" uuid NOT NULL, "sender_id" uuid, "tenant_id" uuid NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_6a72c3c0f683f6462415e653c3a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "email" character varying NOT NULL, "keycloak_id" character varying, "is_active" boolean NOT NULL DEFAULT true, "last_login" TIMESTAMP WITH TIME ZONE, "employee_id" uuid, "tenant_id" uuid NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "UQ_97b5061278a40c1dead71c1b889" UNIQUE ("keycloak_id"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "time_entries" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "clock_in" TIMESTAMP WITH TIME ZONE NOT NULL, "clock_out" TIMESTAMP WITH TIME ZONE, "clock_in_lat" numeric(10,7), "clock_in_lng" numeric(10,7), "clock_in_method" character varying, "is_manual" boolean NOT NULL DEFAULT false, "notes" character varying, "employee_id" uuid NOT NULL, "tenant_id" uuid NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_b8bc5f10269ba2fe88708904aa0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "messages" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "content" text NOT NULL, "is_read" boolean NOT NULL DEFAULT false, "read_at" TIMESTAMP WITH TIME ZONE, "attachment_url" character varying, "sender_id" uuid NOT NULL, "recipient_id" uuid NOT NULL, "tenant_id" uuid NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_18325f38ae6de43878487eff986" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "announcements" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "title" character varying NOT NULL, "content" text NOT NULL, "target_audience" character varying NOT NULL DEFAULT 'ALL', "is_pinned" boolean NOT NULL DEFAULT false, "published_at" TIMESTAMP WITH TIME ZONE, "expires_at" TIMESTAMP WITH TIME ZONE, "author_id" uuid NOT NULL, "tenant_id" uuid NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_b3ad760876ff2e19d58e05dc8b0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "training_enrollments" ("training_id" uuid NOT NULL, "employee_id" uuid NOT NULL, CONSTRAINT "PK_ba5d98de488507e93e4c095fe95" PRIMARY KEY ("training_id", "employee_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_7008685548d0b125fcc0285200" ON "training_enrollments" ("training_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_5f3e6ad2eaa08adfca73d493d0" ON "training_enrollments" ("employee_id") `);
        await queryRunner.query(`ALTER TABLE "departments" ADD CONSTRAINT "FK_ef8a4fb89ff96bbe98f1798798c" FOREIGN KEY ("manager_id") REFERENCES "employees"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "departments" ADD CONSTRAINT "FK_2d6673ae91cee09bef47d2a5de2" FOREIGN KEY ("parent_department_id") REFERENCES "departments"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "departments" ADD CONSTRAINT "FK_146fd7019eea73f8ee7bbb52d4a" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "positions" ADD CONSTRAINT "FK_e413c6578fcdae9a8fd673c5bc7" FOREIGN KEY ("department_id") REFERENCES "departments"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "positions" ADD CONSTRAINT "FK_998367a410208badb017f64e716" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "shifts" ADD CONSTRAINT "FK_47935d717a7c66cb9e8ac08df82" FOREIGN KEY ("employee_id") REFERENCES "employees"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "shifts" ADD CONSTRAINT "FK_90413bab4120ede23bb47168777" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "leaves" ADD CONSTRAINT "FK_d38ef9b49eca9fbedefc35011a6" FOREIGN KEY ("approved_by_id") REFERENCES "employees"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "leaves" ADD CONSTRAINT "FK_29d5827b1f3a86dc19288ec69a5" FOREIGN KEY ("employee_id") REFERENCES "employees"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "leaves" ADD CONSTRAINT "FK_c96f91af78ceeed65da1f0f3d18" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "employees" ADD CONSTRAINT "FK_678a3540f843823784b0fe4a4f2" FOREIGN KEY ("department_id") REFERENCES "departments"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "employees" ADD CONSTRAINT "FK_8b14204e8af5e371e36b8c11e1b" FOREIGN KEY ("position_id") REFERENCES "positions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "employees" ADD CONSTRAINT "FK_bcdf921072a19dd2758a628c5c0" FOREIGN KEY ("manager_id") REFERENCES "employees"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "employees" ADD CONSTRAINT "FK_588d18aeef0504067e40c682788" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payrolls" ADD CONSTRAINT "FK_5145d894f823722a43ec3e1955e" FOREIGN KEY ("employee_id") REFERENCES "employees"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payrolls" ADD CONSTRAINT "FK_d77ef12e0b5bb22d362769b946d" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "job_applications" ADD CONSTRAINT "FK_1f0ed6a45088ef95236af37a5f4" FOREIGN KEY ("job_posting_id") REFERENCES "job_postings"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "job_applications" ADD CONSTRAINT "FK_b6fc22f60e3f6b05b6290398698" FOREIGN KEY ("assigned_to_id") REFERENCES "employees"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "job_applications" ADD CONSTRAINT "FK_5d59a819d473daeea0c14ac5d36" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "job_postings" ADD CONSTRAINT "FK_cf838f9c48f90ad76d0f2d231e5" FOREIGN KEY ("department_id") REFERENCES "departments"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "job_postings" ADD CONSTRAINT "FK_0b25a3ecf04f0eddc2a1f1d299f" FOREIGN KEY ("recruiter_id") REFERENCES "employees"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "job_postings" ADD CONSTRAINT "FK_71549ebdaf6647e51de711396c3" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reviews" ADD CONSTRAINT "FK_c757a01d5b7a356b72238ad6c1c" FOREIGN KEY ("employee_id") REFERENCES "employees"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reviews" ADD CONSTRAINT "FK_92e950a2513a79bb3fab273c92e" FOREIGN KEY ("reviewer_id") REFERENCES "employees"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reviews" ADD CONSTRAINT "FK_bfb7f35d7db2b7afc40811c1925" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "goals" ADD CONSTRAINT "FK_8ff416fb969445fa3e470654c8a" FOREIGN KEY ("employee_id") REFERENCES "employees"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "goals" ADD CONSTRAINT "FK_dc6c5e2227f13de6bf552d58100" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "trainings" ADD CONSTRAINT "FK_03534838c8b2a401abe3611016a" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "FK_5332a4daa46fd3f4e6625dd275d" FOREIGN KEY ("recipient_id") REFERENCES "employees"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "FK_4140c8b09ff58165daffbefbd7e" FOREIGN KEY ("sender_id") REFERENCES "employees"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "FK_d93ddd7e1b890535ecafbb334ec" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_9760615d88ed518196bb79ea03d" FOREIGN KEY ("employee_id") REFERENCES "employees"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_109638590074998bb72a2f2cf08" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "time_entries" ADD CONSTRAINT "FK_ff1c7d297494c0b028320e4f21e" FOREIGN KEY ("employee_id") REFERENCES "employees"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "time_entries" ADD CONSTRAINT "FK_794b624ef3b3b9b07bf3cb3d656" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "messages" ADD CONSTRAINT "FK_22133395bd13b970ccd0c34ab22" FOREIGN KEY ("sender_id") REFERENCES "employees"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "messages" ADD CONSTRAINT "FK_566c3d68184e83d4307b86f85ab" FOREIGN KEY ("recipient_id") REFERENCES "employees"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "messages" ADD CONSTRAINT "FK_558150f45586066db2415eb28c5" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "announcements" ADD CONSTRAINT "FK_0a13cf0aa1f1a2666699ff473f0" FOREIGN KEY ("author_id") REFERENCES "employees"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "announcements" ADD CONSTRAINT "FK_98a574ea395ac0d8c01e562e658" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "training_enrollments" ADD CONSTRAINT "FK_7008685548d0b125fcc0285200e" FOREIGN KEY ("training_id") REFERENCES "trainings"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "training_enrollments" ADD CONSTRAINT "FK_5f3e6ad2eaa08adfca73d493d02" FOREIGN KEY ("employee_id") REFERENCES "employees"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "training_enrollments" DROP CONSTRAINT "FK_5f3e6ad2eaa08adfca73d493d02"`);
        await queryRunner.query(`ALTER TABLE "training_enrollments" DROP CONSTRAINT "FK_7008685548d0b125fcc0285200e"`);
        await queryRunner.query(`ALTER TABLE "announcements" DROP CONSTRAINT "FK_98a574ea395ac0d8c01e562e658"`);
        await queryRunner.query(`ALTER TABLE "announcements" DROP CONSTRAINT "FK_0a13cf0aa1f1a2666699ff473f0"`);
        await queryRunner.query(`ALTER TABLE "messages" DROP CONSTRAINT "FK_558150f45586066db2415eb28c5"`);
        await queryRunner.query(`ALTER TABLE "messages" DROP CONSTRAINT "FK_566c3d68184e83d4307b86f85ab"`);
        await queryRunner.query(`ALTER TABLE "messages" DROP CONSTRAINT "FK_22133395bd13b970ccd0c34ab22"`);
        await queryRunner.query(`ALTER TABLE "time_entries" DROP CONSTRAINT "FK_794b624ef3b3b9b07bf3cb3d656"`);
        await queryRunner.query(`ALTER TABLE "time_entries" DROP CONSTRAINT "FK_ff1c7d297494c0b028320e4f21e"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_109638590074998bb72a2f2cf08"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_9760615d88ed518196bb79ea03d"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "FK_d93ddd7e1b890535ecafbb334ec"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "FK_4140c8b09ff58165daffbefbd7e"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "FK_5332a4daa46fd3f4e6625dd275d"`);
        await queryRunner.query(`ALTER TABLE "trainings" DROP CONSTRAINT "FK_03534838c8b2a401abe3611016a"`);
        await queryRunner.query(`ALTER TABLE "goals" DROP CONSTRAINT "FK_dc6c5e2227f13de6bf552d58100"`);
        await queryRunner.query(`ALTER TABLE "goals" DROP CONSTRAINT "FK_8ff416fb969445fa3e470654c8a"`);
        await queryRunner.query(`ALTER TABLE "reviews" DROP CONSTRAINT "FK_bfb7f35d7db2b7afc40811c1925"`);
        await queryRunner.query(`ALTER TABLE "reviews" DROP CONSTRAINT "FK_92e950a2513a79bb3fab273c92e"`);
        await queryRunner.query(`ALTER TABLE "reviews" DROP CONSTRAINT "FK_c757a01d5b7a356b72238ad6c1c"`);
        await queryRunner.query(`ALTER TABLE "job_postings" DROP CONSTRAINT "FK_71549ebdaf6647e51de711396c3"`);
        await queryRunner.query(`ALTER TABLE "job_postings" DROP CONSTRAINT "FK_0b25a3ecf04f0eddc2a1f1d299f"`);
        await queryRunner.query(`ALTER TABLE "job_postings" DROP CONSTRAINT "FK_cf838f9c48f90ad76d0f2d231e5"`);
        await queryRunner.query(`ALTER TABLE "job_applications" DROP CONSTRAINT "FK_5d59a819d473daeea0c14ac5d36"`);
        await queryRunner.query(`ALTER TABLE "job_applications" DROP CONSTRAINT "FK_b6fc22f60e3f6b05b6290398698"`);
        await queryRunner.query(`ALTER TABLE "job_applications" DROP CONSTRAINT "FK_1f0ed6a45088ef95236af37a5f4"`);
        await queryRunner.query(`ALTER TABLE "payrolls" DROP CONSTRAINT "FK_d77ef12e0b5bb22d362769b946d"`);
        await queryRunner.query(`ALTER TABLE "payrolls" DROP CONSTRAINT "FK_5145d894f823722a43ec3e1955e"`);
        await queryRunner.query(`ALTER TABLE "employees" DROP CONSTRAINT "FK_588d18aeef0504067e40c682788"`);
        await queryRunner.query(`ALTER TABLE "employees" DROP CONSTRAINT "FK_bcdf921072a19dd2758a628c5c0"`);
        await queryRunner.query(`ALTER TABLE "employees" DROP CONSTRAINT "FK_8b14204e8af5e371e36b8c11e1b"`);
        await queryRunner.query(`ALTER TABLE "employees" DROP CONSTRAINT "FK_678a3540f843823784b0fe4a4f2"`);
        await queryRunner.query(`ALTER TABLE "leaves" DROP CONSTRAINT "FK_c96f91af78ceeed65da1f0f3d18"`);
        await queryRunner.query(`ALTER TABLE "leaves" DROP CONSTRAINT "FK_29d5827b1f3a86dc19288ec69a5"`);
        await queryRunner.query(`ALTER TABLE "leaves" DROP CONSTRAINT "FK_d38ef9b49eca9fbedefc35011a6"`);
        await queryRunner.query(`ALTER TABLE "shifts" DROP CONSTRAINT "FK_90413bab4120ede23bb47168777"`);
        await queryRunner.query(`ALTER TABLE "shifts" DROP CONSTRAINT "FK_47935d717a7c66cb9e8ac08df82"`);
        await queryRunner.query(`ALTER TABLE "positions" DROP CONSTRAINT "FK_998367a410208badb017f64e716"`);
        await queryRunner.query(`ALTER TABLE "positions" DROP CONSTRAINT "FK_e413c6578fcdae9a8fd673c5bc7"`);
        await queryRunner.query(`ALTER TABLE "departments" DROP CONSTRAINT "FK_146fd7019eea73f8ee7bbb52d4a"`);
        await queryRunner.query(`ALTER TABLE "departments" DROP CONSTRAINT "FK_2d6673ae91cee09bef47d2a5de2"`);
        await queryRunner.query(`ALTER TABLE "departments" DROP CONSTRAINT "FK_ef8a4fb89ff96bbe98f1798798c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5f3e6ad2eaa08adfca73d493d0"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7008685548d0b125fcc0285200"`);
        await queryRunner.query(`DROP TABLE "training_enrollments"`);
        await queryRunner.query(`DROP TABLE "announcements"`);
        await queryRunner.query(`DROP TABLE "messages"`);
        await queryRunner.query(`DROP TABLE "time_entries"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TABLE "notifications"`);
        await queryRunner.query(`DROP TYPE "public"."notifications_type_enum"`);
        await queryRunner.query(`DROP TABLE "trainings"`);
        await queryRunner.query(`DROP TABLE "goals"`);
        await queryRunner.query(`DROP TABLE "reviews"`);
        await queryRunner.query(`DROP TABLE "job_postings"`);
        await queryRunner.query(`DROP TYPE "public"."job_postings_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."job_postings_employment_type_enum"`);
        await queryRunner.query(`DROP TABLE "job_applications"`);
        await queryRunner.query(`DROP TYPE "public"."job_applications_status_enum"`);
        await queryRunner.query(`DROP TABLE "payrolls"`);
        await queryRunner.query(`DROP TYPE "public"."payrolls_status_enum"`);
        await queryRunner.query(`DROP TABLE "employees"`);
        await queryRunner.query(`DROP TYPE "public"."employees_role_enum"`);
        await queryRunner.query(`DROP TYPE "public"."employees_status_enum"`);
        await queryRunner.query(`DROP TABLE "leaves"`);
        await queryRunner.query(`DROP TYPE "public"."leaves_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."leaves_type_enum"`);
        await queryRunner.query(`DROP TABLE "shifts"`);
        await queryRunner.query(`DROP TYPE "public"."shifts_status_enum"`);
        await queryRunner.query(`DROP TABLE "positions"`);
        await queryRunner.query(`DROP TABLE "departments"`);
        await queryRunner.query(`DROP TABLE "tenants"`);
    }

}
